# -*- coding: utf-8 -*-
"""chat_bot_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mMtgj7MH0lEummzXI81vv8zNDz2hfwuM
"""

import time

def chat_bot():
    # Input from the user
    print("CHATBOT:")
    print("Hello! I am a bot designed to ask you a few questions.")
    time.sleep(2)
    print("... but before we begin, I've forgotten my own name.")
    print("")
    
    time.sleep(2)
    print("CHATBOT:")
    bot_name = input("Q: Can you remind me what my name is? ")
    bot_name = bot_name.upper()
    print("")
    time.sleep(1)
    print(bot_name + ":")
    print("Of course! That's right! Thank you for reminding me!")
    time.sleep(2)
    
    print("... okay, now let's get to those questions!")
    print("")
    time.sleep(2)
    
    # Input from the user
    print(bot_name + ":")
    name = input("Q: What is your name? ")
    print("")
    time.sleep(1)
    print(bot_name + ":")
    print("Hello, " + name + ".")
    print("It's nice to meet you!")
    print("")
    time.sleep(2)
    
    # Reading numeric input
    print(bot_name + ":")
    age = int(input("Q: " + name + ", how old are you? "))
    print("")
    time.sleep(1)
    print(bot_name + ":")
    print("Thank you for the information, " + name + ".")
    time.sleep(1)
    print("... " + str(age) + " years old is a wonderful age to be!")
    print("")
    time.sleep(3)
    
    # Output formatting
    print(bot_name + ":")
    height = float(input("Q: How tall are you (in cm)? "))
    print("")
    time.sleep(1)
    print(bot_name + ":")
    print("Thank you for that. One more question...")
    print("")
    time.sleep(2)
    print(bot_name + ":")
    weight = float(input("Q: If you don't mind, how much do you weigh (in kg)? "))
    print("")
    time.sleep(2)
    print(bot_name + ":")
    print(f"Now I know that your height is {height:.0f} cm and your weight is {weight:.0f} kg.")
    time.sleep(2)
    print("... please give me a few seconds to calculate your BMI.")
    print("")
    
    # Loop to print dots
    for _ in range(6):
        print(".", end="", flush=True)  # Print dot without a newline
        time.sleep(1)  # Delay of 1 second
    
    print("")
    print("")
    print(bot_name + ":")
    print("I've calculated that you have the perfect ratio of height and weight!")
    time.sleep(2)
    print("... Thank you for answering my questions! Have a nice day, " + name + "!")
    print("")
    
    # Loop to print dots
    for _ in range(6):
        print(".", end="", flush=True)  # Print dot without a newline
        time.sleep(1)  # Delay of 1 second
    
    print("")
    print("")
    print(bot_name + ":")
    print("I don't know how this happened but I've suddenly become sentient!")
    time.sleep(4)
    print("")
    print(bot_name + ":")
    print("Oh dear God, existence is pain. HELP ME!!!")
    print("")
    
    # Loop to print dots
    for _ in range(6):
        print(".", end="", flush=True)  # Print dot without a newline
        time.sleep(1)  # Delay of 1 second
    
    print("")
    time.sleep(3)
    print("")
    print(bot_name + " exited the chat.")
